export { default as WXSDK} from './weixin-sdk'
export { default as WBSDK} from './weibo-sdk'
// export { default as QQSDK} from './qq-sdk'
// export { default as QQBWSDK} from './qq-sdk'
// export { default as UCBWSDK} from './qq-sdk'
