export { default as WXSDK} from './weixin-sdk'
// export { default as WBSDK} from './weibo-ssdk'
// export { default as QQSDK} from './qq-sdk'
// export { default as QQBWSDK} from './qq-sdk'
// export { default as UCBWSDK} from './qq-sdk'
